import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.scss";
import Navbar from "./components/Navbar";

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Dashboard UI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${styles.container}`}>
        <Navbar className={styles.navbar} />
        {children}
      </body>
    </html>
  );
}
